cilium:

  k8sServiceHost: 192.168.80.20
  k8sServicePort: 6443

  kubeProxyReplacement: true

  # Support GatewayAPI
  gatewayAPI:
    enabled: true

  l2announcements:
    enabled: true

  externalIPs:
    enabled: true

  k8sClientRateLimit:
    qps: 50
    burst: 200

  hubble:
    relay: 
      enabled: true
    ui:
      enabled: true

  operator:
    rollOutPods: true

  rollOutCiliumPods: true

