apiVersion: v2
name: cert-manager
description: cert-manager chart
type: application
version: 0.1.0
appVersion: "1.12.2"
dependencies:
  - name: cert-manager
    version: "1.12.2"
    repository: https://charts.jetstack.io
